In [44]:
import numpy as np
from keras.models import load_model
model = load_model('nn.h5')

layer_no =1;
a = model.get_layer(layer_no)

nRecordings = 10
nSamples=100
# randomly sample from the first hidden layer

rand_l1_inds = np.random.choice(range(model.layers[1].output_dim), size=nRecordings, replace=True)
rand_o_inds = np.random.choice(range(model.layers[3].output_dim), size=nRecordings, replace=True)

# if you have not observed some random units
if len(np.unique(rand_o_inds))<model.layers[3].output_dim:
    #pick #outputs random places and replace them with 1:#outputs.
    rand_o_inds[np.random.choice(range(nRecordings), size =model.layers[3].output_dim, replace=False)] = range(10)
    
# split the data in nRecordings

X_rec =  np.random.rand(nSamples, 100)

X_rec = X_rec[np.random.choice(range(nSamples), size= nSamples, replace=False), :]                         
X_rec_pr = np.nan*np.ones(X_rec.shape)


sample_ind =0;
slice_size = nSamples/nRecordings
for iRec in range(nRecordings):
    inds = np.array(range(sample_ind,((iRec+1)*slice_size)))
    sample_ind = sample_ind + slice_size
    print(inds)
    a = np.array([rand_o_inds[iRec], rand_l1_inds[iRec]])
    X_rec_pr[inds[:, None], a] = X_rec[inds[:, None], a]
    print(X_rec_pr[inds[:, None], a])

[0 1 2 3 4 5 6 7 8 9]
[[ 0.02908675  0.27939118]
 [ 0.07819866  0.72844547]
 [ 0.11350266  0.81822668]
 [ 0.98848499  0.2747778 ]
 [ 0.91648773  0.44293387]
 [ 0.43226685  0.03049473]
 [ 0.65011252  0.99624759]
 [ 0.82304508  0.23438152]
 [ 0.93543001  0.64545679]
 [ 0.67197561  0.69434229]]
[10 11 12 13 14 15 16 17 18 19]
[[ 0.87550593  0.08165641]
 [ 0.71521941  0.60603582]
 [ 0.42078186  0.58188145]
 [ 0.81945928  0.31105556]
 [ 0.02134548  0.57794956]
 [ 0.68707653  0.96257841]
 [ 0.07465525  0.47194392]
 [ 0.69535757  0.14595397]
 [ 0.05823954  0.03426315]
 [ 0.52790448  0.13246906]]
[20 21 22 23 24 25 26 27 28 29]
[[ 0.06181799  0.6085432 ]
 [ 0.2318412   0.84796178]
 [ 0.25170007  0.55785045]
 [ 0.02550106  0.56750077]
 [ 0.24629265  0.19667295]
 [ 0.28809015  0.41709512]
 [ 0.29277977  0.21877056]
 [ 0.04593109  0.52290598]
 [ 0.67021635  0.29399477]
 [ 0.21712693  0.88517115]]
[30 31 32 33 34 35 36 37 38 39]
[[ 0.13683101  0.33138979]
 [ 0.68601808  0.73732467]
 [ 0.15349912  

array([[ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       ..., 
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan]])

In [ ]:
X_rec_pr.shape